### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by danr** [occivink/config#2]
No LICENSE or UNLICENSE! :)

**Comment by occivink** [comment]
That's a fair point, but with the dotfiles management scheme I use (close to [this](https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/)) I'd have to put the LICENSE file directly into my $HOME which is a bit eeeeh. Any ideas?

**Comment by danr** [comment]
I can't help but smile about the idea of a LICENSE file directly in $HOME ;) But I cannot think of any sensible workaround right now... *sigh*
